# Generated by Django 2.2.2 on 2019-06-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190627_1834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(help_text='enter the language in which the given book is available', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First'),
        ),
    ]
